# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'XLLogerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XLLogerDemo
  pod "XLLoger", :path => "../"

  target 'XLLogerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XLLogerDemoUITests' do
    # Pods for testing
  end

end
